#!/usr/bin/env python3
"""Fetch Philip Ruppert's works from ORCID, resolve DOIs to citations,
write a year-grouped Markdown partial (_publications.md).

Stdlib only. Run: python scripts/fetch_orcid.py
"""
from __future__ import annotations
import json
import sys
import urllib.request
from collections import defaultdict
from pathlib import Path

ORCID = "0000-0002-4028-8200"
WORKS_URL = f"https://pub.orcid.org/v3.0/{ORCID}/works"
OUT = Path(__file__).resolve().parent.parent / "_publications.md"
TIMEOUT = 30


def _get(url: str, accept: str) -> bytes:
    req = urllib.request.Request(url, headers={"Accept": accept, "User-Agent": "pr-website/1.0"})
    with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
        return r.read()


def fetch_dois_and_titles() -> list[dict]:
    """Return [{doi, title, year}] from ORCID work-group summaries."""
    data = json.loads(_get(WORKS_URL, "application/json"))
    items = []
    for group in data.get("group", []):
        summary = group["work-summary"][0]
        title = (((summary.get("title") or {}).get("title")) or {}).get("value", "")
        yd = (summary.get("publication-date") or {}).get("year") or {}
        year = yd.get("value") if yd else None
        doi = None
        for eid in ((summary.get("external-ids") or {}).get("external-id") or []):
            if eid.get("external-id-type", "").lower() == "doi":
                doi = (eid.get("external-id-value") or "").strip()
                break
        items.append({"doi": doi, "title": title, "year": year})
    return items


def bold_author(name: str) -> str:
    return f"**{name}**" if "ruppert" in name.lower() else name


def _author_list(csl: dict) -> str:
    names = []
    for a in csl.get("author", []) or []:
        given, family = a.get("given", ""), a.get("family", "")
        full = (f"{given} {family}").strip() or a.get("literal", "")
        if full:
            names.append(bold_author(full))
    if len(names) > 8:
        names = names[:8] + ["et al."]
    return ", ".join(names)


def format_citation(csl: dict) -> str:
    authors = _author_list(csl)
    title = (csl.get("title") or "").rstrip(".")
    journal = csl.get("container-title", "")
    year = ""
    issued = (csl.get("issued") or {}).get("date-parts") or []
    if issued and issued[0] and issued[0][0] is not None:
        year = str(issued[0][0])
    doi = csl.get("DOI", "")
    parts = []
    if authors:
        parts.append(authors + ".")
    parts.append(f"*{title}*.")
    if journal:
        parts.append(f"{journal}")
    if year:
        parts.append(f"{year}.")
    line = " ".join(parts)
    if doi:
        line += f" [https://doi.org/{doi}](https://doi.org/{doi})"
    return line


def resolve(doi: str) -> dict | None:
    try:
        raw = _get(f"https://doi.org/{doi}", "application/vnd.citationstyles.csl+json")
        return json.loads(raw)
    except Exception as e:  # noqa: BLE001
        print(f"  ! DOI resolve failed for {doi}: {e}", file=sys.stderr)
        return None


def year_of(csl_or_item) -> int:
    issued = (csl_or_item.get("issued") or {}).get("date-parts") or []
    if issued and issued[0] and issued[0][0] is not None:
        return int(issued[0][0])
    y = csl_or_item.get("year")
    return int(y) if y else 0


def main() -> int:
    items = fetch_dois_and_titles()
    print(f"ORCID returned {len(items)} work groups", file=sys.stderr)
    by_year: dict[int, list[str]] = defaultdict(list)
    for it in items:
        csl = resolve(it["doi"]) if it["doi"] else None
        if csl:
            by_year[year_of(csl)].append(format_citation(csl))
        else:
            # fallback: title + year only, no citation metadata
            yr = int(it["year"]) if it["year"] else 0
            line = f"*{(it['title'] or 'Untitled').rstrip('.')}*. {it['year'] or ''}".strip()
            by_year[yr].append(line)
    lines = ["<!-- generated by scripts/fetch_orcid.py — do not edit by hand -->", ""]
    for yr in sorted(by_year, reverse=True):
        header = str(yr) if yr else "Other"
        lines.append(f"### [{header}]{{.pub-year}}")
        lines.append("")
        for c in by_year[yr]:
            lines.append(f"- {c}")
        lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({sum(len(v) for v in by_year.values())} entries)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
